Crud
AshirMohab/holiday-planner-angular pull request #6
Opened 2022-04-21 09:03 UTC by AshirMohab

Very jank fix to reloading state

2022-04-21 14:52 UTC, AshirMohab commented
Added lazy loading as well as state management for the currency api. The site is somewhat responsive as well

2022-04-22 06:10 UTC, theadley requested changes
Looks like a great PR. It's a bit long for a PR, so keep that in mind.
The majority of my comments are for removing commented out code, so be mindful of not committing commented out code. Git is your friend if you need to dig into the past.

2022-04-22 06:10 UTC, theadley commented on src/app/services/user.service.ts
>    async deleteUser(userID: string) {
Is this used? By what effect? async await is not compatible with state management.

2022-04-22 06:10 UTC, theadley commented on src/app/store/currency/currency.selectors.ts
> +  );
It looks like you need to still add the selectors for all of the currencies and the selected currency

2022-04-22 06:10 UTC, theadley commented on src/app/store/trip/trip.effects.ts
> +        // const currentUser = { uid: 'yDYYtFyxd3QqkA9FTevxOOC7Suy2' };
Commented out code to be removed please

2022-04-22 06:10 UTC, theadley commented on src/app/store/trip/trip.effects.ts
> +        this.tripService.editUserTrip(tripToRemove).pipe(
Why is removeUserTrip calling editUserTrip? Doesn't it need the tripId first?

2022-04-22 06:10 UTC, theadley commented on src/app/store/trip/trip.selectors.ts
> +// import { selectTripItineraries } from '../itinerary/itinerary.selectors';
Commented out code to be removed please

2022-04-22 06:53 UTC, AshirMohab commented on src/app/components/itinerary/my-itineraries/my-itineraries.component.ts
> +  ngOnInit(): void {}
This just takes in the list of itinerary items of a trip and then will display them

2022-04-22 09:21 UTC, AshirMohab commented on src/app/lazy/lazy.component.ts
> +export class LazyComponent implements OnInit {
I know but it was just helping me know what was up

2022-04-22 09:24 UTC, AshirMohab commented on src/app/services/auth.service.ts
>    get isLoggedIn(): boolean {
Just checked it, doesn't seem to constantly run

2022-04-22 11:38 UTC, theadley approved these changes
Good soup

2022-04-22 11:53 UTC, merged